[package]
name = "tforge-config"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_with = { workspace = true }
toml = { version = "0.8.12" }
anyhow = { workspace = true }